FROM nikolaik/python-nodejs:latest
RUN uname -a

# make the 'app' folder the current working directory
WORKDIR app/

# copy both 'package.json' and 'package-lock.json' (if available)
COPY ./package*.json ./

# install project dependencies leaving out dev dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

EXPOSE 8080
EXPOSE 443

# RUN npx mongoosejs-cli db:seed:all
CMD [ "node", "index.js" ]
